# Generated by Django 5.0.1 on 2024-01-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-last_update']},
        ),
    ]
